### ISSUE TITLE
Enable students to view the grades.

### ISSUE THREAD

**Issue by apollonorth** [apollonorth/GitHubFlow#1]
**User Story**
As a student, I want to be able to view my grades in order to better track and manage my academics. 

**Detailed Description**
Students should be able to easily access their grades for all the courses they are enrolled in for the semester. This will allow students to understand how they are doing academically and make adjustments if necessary.
 
**Tasks**
- [x] Create UI for students to view grades.
- [x] Create API connection to get grades from database.
- [x] Create login for students.

**Acceptance Criteria**
* Only works on Safari, Chrome, and Edge.
* Each student only needs to see grades for currently enrolled classes.
* Student does not need to know if grade is final or not.

**Acceptance Tests**
1. A student is able to securely login.
2. A student can switch between classes.
3. A student can see the individual assignment and exam scores contributing to overall grade.
4. A student is able to see the grade statistics (mean, median, high, low).
